### ISSUE TITLE
Build Container WebApp Endpoint

### ISSUE THREAD

**Issue by BenGalewsky** [funcx-faas/funcx-container-service#11]
_As a DLHub user I want to submit a specification so my container can be built for me_

We will add a new endpoint where a user can provide a Repo2Docker style specification for a new container to be built.

Payload to the new POST endpoint: `/containers/build/:
```json
"type": "docker",
"specification": {
      "apt": ["apt package 1", "apt-package 2"],
      "pip":["pypi library", "pypi library==specific version"],
      "conda": ["conda dependency", "conda dependency==specific version"]
}
```

## Acceptance Criteria
Given I have a valid docker container specification JSON When I submit to the WebService Then I receive a container UUID and a container record is created and the specification is persisted with a status of _Submitted_.

## Assumptions
1. Does not support _advanced build_ (tarball) containers
2. `type` must be "docker"
3. Add `specification` property to `Container` model:  JSON container build specification
4. Add a `status` property to the `Container` model. Valid states are "Submitted", "Building", "Build Failed", "Ready"

**Comment by BenGalewsky** [comment]
FuncX Project Story: https://app.shortcut.com/funcx/story/9607/create-container-via-webservice

**Comment by blue442** [comment]
To create a fully functional `/build` route in the container service and fulfill the user story for this issue, the following functionality must be completed:
- [x] modify container model specification as described in this issue
- [x] develop callbacks to replace DB calls with calls back to webservice APIs
- [x] remove references to DB calls in the container service
- [x] create unit and integration (at the level of individual routes) tests

**Comment by BenGalewsky** [comment]
@blue442 - you could create a funcXAdapater class to handle interactions back with the funcX WebService. For now these could be mocked out, but at least it would formalize the interactions between the two micro services
