### ISSUE TITLE
Container Service Accepts Zip File

### ISSUE THREAD

**Issue by BenGalewsky** [funcx-faas/funcx-container-service#22]
_As a container Service user I want a provided zip file bundled into the image so I can use assets that are otherwise not installable_

## Assumptions
1. The container spec will include a readable URL to the zip file. This will usually be a signed S3 URL
2. Creating the signed URL is out of scope of funcX
3. We will extend DLHub API to create a writable URL for the client to save the zip file and then a readable URL for container service to load the zip file.

**Comment by blue442** [comment]
Looking into this I've been trying to figure out the best way to transfer the container spec and the zip file from the web service to the container service, and it doesn't look like there is any way to combine the json representation of the container spec in the body of the request (as we have it now) with an associated file. From what I can tell, there are four choices:

1) base64 encode the file and add it to the json in the body of the request

2) perform 2 requests to the container service - one that registers the build spec and one that submits the file (both requests can contain the uuid provided by the web service so they can be paired by the server)

3) convert the request from a `application/json' type to use a form construct which appears to be able to combine the two into a single request - [this SO answer](https://stackoverflow.com/a/70640522/4280160) describes it better than I could, but it looks relatively straightforward to implement.

4) package the container spec into a file, and include that file (along with a zip file) in the request (total of 2 files).

My instinctual response is that 1) is no good, and 3) might be more straightforward than 2), but wanted to check in with you to see if you had other suggestions or thoughts about the whole thing. Just thought of 4 - might be a pretty simple solution.

**Comment by ascourtas** [comment]
Thanks for the context @blue442, I haven't had a chance to research this yet (tomorrow is my DLHub/container service day this week), but without digging in my instinctual response is that 4) sounds like a good option. 

In the current implementation of DLHub, the actual function to execute as a servable (in, say, a .py file) gets zipped along with the Dockerfile defining the container, environment-defining files (eg requirements.txt, environment.yaml),  and dlhub.json (a JSON config that contains the funcx_token, servable info, publisher metadata etc). So, 1 zip file.

From just briefly looking at things, it sounds like 4) packaging the container spec in a file included in the request with the zip (total of 2 files) would be conceptually quite similar, is that right?

**Comment by blue442** [comment]
Hey @ascourtas - I do think that sounds similar - my only concern for that approach would be that the schema for the request sent by the web service to the container service isn't explicitly defined in the api service. This means that the schema of the container spec isn't explicitly spelled out in the API docs, and isn't subjected to pydantic's type checking on submission of the request. That said, we've only got one 'user' of the container service API (the web service) so manually communicating the container spec for the image should be doable - I'm not certain that the pydantic checking would be an option for processing form data anyway (#3 from above), so as long as everyone is in agreement on that approach, I can modify the container service to take a zip file containing a json file that has the container spec, and a zip file that contains whatever payload is needed in the image for running the functionality via funcx (I think this would be the servable and the dlhub.json - but whatever it is, I'll just pass it to repo2docker).

Let me know if that sounds like how we want to proceed and I'll make the appropriate changes (or ping me if there are q's).

**Comment by ascourtas** [comment]
@blue442 I feel ok about this approach, @BenGalewsky how about you?

**Comment by ascourtas** [comment]
of note @blue442 I believe Ben G wanted me to try to take a crack at modifying the container service to take the zip file so that I could get introduced to the codebase and start working with ya'll. So I am happy to try to implement that, but if you or @BenGalewsky think it would be better if I tried picking up a different issue then that's AOK by me.

**Comment by blue442** [comment]
Hey @ascourtas - sorry - I've been swamped - I think that would be great! If you just want to jump in and start poking around, https://github.com/funcx-faas/funcx-container-service/commit/7377b4e1664498fa85764ff230a8ce8c6d293d10 would be the place to start, or I'm happy to jump on a call some time next week to help orient you if that would be useful - just let me know!

**Comment by BenGalewsky** [comment]
In discussion with @ryanchard  it seems that in the past users have wanted to publish very large zip files with their models. He was thinking it might be better to stream the zip file to S3 and then just point the container service at the saved object

**Comment by BenGalewsky** [comment]
We had a robust discussion of this at today's ContainerService call. I'm updating the story to math our plan for moving forward
