### ISSUE TITLE
Container Service Status Updates on Failure

### ISSUE THREAD

**Issue by BenGalewsky** [funcx-faas/funcx-container-service#25]
# Problem
When the container service build fails, no status update is sent to the WebService. The status of the build remains _building_

**Comment by blue442** [comment]
Solved this along with the issue of stderr messaging being sent to webservice upon successful completion (https://github.com/funcx-faas/funcx-container-service/commit/70032fa476e64bb73249f507f29c39eb95ac3f57 and the preceeding commit). It appears that repo2docker only communicates on stderr? These fixes have been pushed to image_2_registry branch, but I wasn't able to get the two services running and communicating yet so they haven't been merged to dev.
