### ISSUE TITLE
Remove exit() from the code

### ISSUE THREAD

**Issue by BenGalewsky** [funcx-faas/funcx-container-service#33]
There are a few error conditions that end with a sys.exit(-1).

These will cause the entire server to stop. Remove

**Comment by blue442** [comment]
Removed calls to sys.exit with 5fed3759b0f2a5f376df98ec646aa7a60055f8c6 - although through testing I can't find any instance where that disrupts the running service (specifying multiple uvicorn workers, not specifying workers, calling sys.exit() async, in task, or directly). 

It looks like the sys.exit() is limited to exiting the python program, not killing the workers.
