### ISSUE TITLE
investigate callback 422 in container-service

### ISSUE THREAD

**Issue by blue442** [funcx-faas/funcx-container-service#50]

**Comment by blue442** [comment]
After closer examination, this issue ls reported when the callback functions of the container service api try to supply a status update using a PUT request back to the funcx web service, but that message is not received. We initially saw this when testing the container service locally, as there was no web service running for it to communicate with. We also see this in the current deployment of container service in funcx, but thusfar it appears to be a discrepancy between what is contained in the body of the PUT from container service and the requirements as stipulated in the web service (enforced by pydantic/fastAPI). I believe in this instance the 422 is the appropriate response code (given the mismatch between the supplied and expected messages) and is operating as expected.

**Comment by ascourtas** [comment]
Response is appropriate, Ben G is on the web service side of it

**Comment by ascourtas** [comment]
Ben G fixed on web service end of things in funcx -- merged into dev and main, funcx release going out today
